- name: bug
  color: d73a4a
  description: 不具合の追跡に使用するラベル
- name: enhancement
  color: a2eeef
  description: 新機能や改善提案のラベル
- name: documentation
  color: 0075ca
  description: ドキュメント更新や整備用のラベル
- name: qa
  color: fbca04
  description: QA作業やテスト確認のラベル
- name: research
  color: c5def5
  description: 調査やSpikeタスクを示すラベル
- name: technical
  color: 60c6c8
  description: 技術的負債の解消や内部タスクのラベル
