- name: bug
  color: d73a4a
  description: 不具合の追跡に使用するラベル
- name: enhancement
  color: a2eeef
  description: 新機能や改善提案のラベル
- name: documentation
  color: 0075ca
  description: ドキュメント更新や整備用のラベル
- name: qa
  color: fbca04
  description: QA作業やテスト確認のラベル
- name: research
  color: c5def5
  description: 調査やSpikeタスクを示すラベル
- name: technical
  color: 60c6c8
  description: 技術的負債の解消や内部タスクのラベル
- name: phase:0
  color: bfd4f2
  description: フェーズ0（プロジェクト基盤）のラベル
- name: phase:1
  color: c0e6c9
  description: フェーズ1（MVP）のラベル
- name: phase:2
  color: f5c6ff
  description: フェーズ2（DX/運用拡張）のラベル
- name: backlog
  color: cfd3d7
  description: バックログ項目のラベル
