services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      SIGNALING_ALLOWED_ORIGINS: http://localhost:5173,http://127.0.0.1:5173

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    environment:
      VITE_SIGNALING_WS_URL: ws://backend:8080/ws
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules

volumes:
  frontend_node_modules:
