name: Backend

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Run formatter check
        run: make backend/lint

      - name: Run tests
        run: make backend/test
